steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/khelo-405317/khelo', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/khelo-405317/khelo']
